# -*- coding: utf-8 -*-
"""Compile config/platform.yaml -> data/config/platform.runtime.json and Hermes artifacts."""

from __future__ import annotations

import json
import os
import shutil
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
def _skill_path(mount: str) -> str:
    """Runtime is consumed inside n8n container — always use container paths."""
    return f"/data/config/skills/{mount}"


def _load_platform(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def build_runtime(platform: dict, repo_root: Path) -> dict:
    engines = platform.get("engines") or {}
    copy = engines.get("copy") or {}
    svg = engines.get("svg") or {}
    render = engines.get("render") or {}
    platforms = engines.get("platforms") or {}
    publish = platform.get("publish") or {}
    features = platform.get("features") or {}

    runtime = {
        "version": platform.get("version", 1),
        "ui": platform.get("ui") or {},
        "orchestration": platform.get("orchestration") or {},
        "engines": {
            "copy": {
                **copy,
                "skill_path": _skill_path(copy.get("skill_mount", "claude_copywriter")),
            },
            "svg": {
                **svg,
                "skill_path": _skill_path(svg.get("skill_mount", "codex_svg_artist")),
            },
            "render": render,
            "platforms": {},
        },
        "publish": publish,
        "features": features,
        "paths": {
            "repo_root_host": str(repo_root.resolve()),
            "data_root": "/data",
            "runs": "/data/runs",
            "logs": "/data/logs",
            "signal_file": publish.get("circuit_breaker", {}).get("signal_file")
            or publish.get("signal_file")
            or "/data/logs/api_dead.json",
        },
    }
    for p_name, p_cfg in platforms.items():
        writer = p_cfg.get("writer") or {}
        artist = p_cfg.get("artist") or {}
        runtime["engines"]["platforms"][p_name] = {
            "writer": {
                **writer,
                "skill_path": _skill_path(writer.get("skill_mount", f"{p_name}_writer")),
            },
            "artist": {
                **artist,
                "skill_path": _skill_path(artist.get("skill_mount", f"{p_name}_artist")),
            },
        }
    return runtime


def write_context_md(runtime: dict, out: Path) -> None:
    engines = runtime.get("engines") or {}
    copy = engines.get("copy") or {}
    svg = engines.get("svg") or {}
    publish = runtime.get("publish") or {}
    p_eng = (engines.get("platforms") or {})
    lines = [
        "# Auto Media Context (generated by amctl apply)",
        "",
        "Do not edit by hand. Source: config/platform.yaml",
        "",
        f"- copy provider: {copy.get('provider')} | skill: {copy.get('skill_mount')} | status: {copy.get('status')}",
        f"- svg provider: {svg.get('provider')} | skill: {svg.get('skill_mount')} | status: {svg.get('status')}",
        f"- publish.mode: {publish.get('mode')}",
        "",
        "- platform skills:",
    ]
    for name, cfg in p_eng.items():
        w = (cfg or {}).get("writer", {})
        a = (cfg or {}).get("artist", {})
        lines.append(f"  - {name}: writer={w.get('skill_mount')} artist={a.get('skill_mount')}")
    lines.extend([
        "",
        "Plan B: read /data/logs/api_dead.json when publish fails.",
        "",
    ])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")


def write_mcp_json(runtime: dict, out: Path) -> None:
    mode = (runtime.get("publish") or {}).get("mode", "auto")
    enable_dom = mode in ("dom", "auto")
    doc = {"mcpServers": {}}
    doc["mcpServers"]["automedia"] = {
        "command": "python3",
        "args": ["/data/scripts/mcp_automedia.py"],
        "env": {
            "AUTO_MEDIA_ROOT": "/data",
            "DATA_ROOT": "/data",
            "AUTO_MEDIA_MCP_WRITE": "0",
        },
    }
    if enable_dom:
        doc["mcpServers"]["playwright"] = {
            "command": "npx",
            "args": ["-y", "@playwright/mcp@latest"],
        }
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def validate_billing(platform: dict) -> list[str]:
    errors: list[str] = []
    engines = platform.get("engines") or {}
    for key in ("copy", "svg"):
        engine = engines.get(key) or {}
        billing = engine.get("billing", "subscription_cli")
        if billing == "metered_api":
            errors.append(
                f"engines.{key}.billing=metered_api is not allowed (subscription_cli only)"
            )
        provider = engine.get("provider", "")
        if "metered" in provider or provider.endswith("_api"):
            if provider not in ("meta_graph_api",):
                errors.append(f"engines.{key}.provider={provider} looks like metered API")
    return errors


PROVIDER_BINARIES: dict[str, str] = {
    "claude_cli": "claude",
    "codex_cli": "codex",
    "gemini_cli": "gemini",
}


def validate_engine_binaries(platform: dict) -> tuple[list[str], list[str]]:
    """Return (errors, warnings) for CLI providers when not in mock mode."""
    if os.environ.get("AUTO_MEDIA_MOCK") == "1":
        return [], []
    if os.environ.get("AUTO_MEDIA_ALLOW_MISSING_CLI") == "1":
        return [], []

    errors: list[str] = []
    warnings: list[str] = []
    engines = platform.get("engines") or {}

    for key in ("copy", "svg"):
        engine = engines.get(key) or {}
        if engine.get("status") != "active":
            continue
        provider = engine.get("provider", "")
        if provider not in PROVIDER_BINARIES:
            continue
        binary = engine.get("binary") or PROVIDER_BINARIES[provider]
        if shutil.which(binary):
            continue
        msg = (
            f"engines.{key}.provider={provider} requires '{binary}' in PATH; "
            "install in Dev Container / n8n image, set AUTO_MEDIA_MOCK=1, "
            "or AUTO_MEDIA_ALLOW_MISSING_CLI=1 for devcontainer post-create"
        )
        errors.append(msg)

    return errors, warnings


def sync_env_example(repo_root: Path) -> None:
    example = repo_root / ".env.example"
    env = repo_root / ".env"
    if not env.exists() and example.exists():
        env.write_text(example.read_text(encoding="utf-8"), encoding="utf-8")


def main() -> int:
    repo = Path(os.environ.get("AUTO_MEDIA_ROOT", REPO_ROOT))
    platform_path = repo / "config" / "platform.yaml"
    if not platform_path.exists():
        print(f"error: missing {platform_path}", file=sys.stderr)
        return 1

    platform = _load_platform(platform_path)
    errors = validate_billing(platform)
    bin_errors, warnings = validate_engine_binaries(platform)
    errors.extend(bin_errors)
    for w in warnings:
        print(f"warn: {w}", file=sys.stderr)
    for e in errors:
        print(f"error: {e}", file=sys.stderr)
    if errors:
        return 1

    runtime = build_runtime(platform, repo)

    runtime_path = repo / "data" / "config" / "platform.runtime.json"
    runtime_path.parent.mkdir(parents=True, exist_ok=True)
    runtime_path.write_text(
        json.dumps(runtime, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    write_context_md(runtime, repo / "config" / "hermes" / "CONTEXT.md")
    write_mcp_json(runtime, repo / "config" / "hermes" / "mcp.json")
    sync_env_example(repo)

    print(str(runtime_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
